let currentDate = new Date()
// console.log(typeof currentDate)
// console.log(currentDate.getFullYear())
// console.log(currentDate.getHours())
// console.log(currentDate.getMilliseconds())
// console.log(currentDate.getTimezoneOffset())
// console.log(currentDate.toLocaleString())
// console.log(currentDate.getHours())
